/**
 * Global Constants
 * Centralized constants used across the application
 */

// Security Types
const SECURITY_TYPES = {
  EQUITY: 'EQUITY',
  FUTURES: 'FUTURES',
  OPTIONS: 'OPTIONS',
  COMMODITY: 'COMMODITY',
  CURRENCY: 'CURRENCY',
  BOND: 'BOND',
  ETF: 'ETF',
  MUTUAL_FUND: 'MUTUAL_FUND'
};

// Array of all security types (for validation)
const SECURITY_TYPES_ARRAY = Object.values(SECURITY_TYPES);

// Derivative security types (require strike price and expiry)
const DERIVATIVE_TYPES = [SECURITY_TYPES.OPTIONS, SECURITY_TYPES.FUTURES];

// Non-derivative security types
const NON_DERIVATIVE_TYPES = [
  SECURITY_TYPES.EQUITY,
  SECURITY_TYPES.BOND,
  SECURITY_TYPES.ETF,
  SECURITY_TYPES.MUTUAL_FUND,
  SECURITY_TYPES.COMMODITY,
  SECURITY_TYPES.CURRENCY
];

// Transaction Types
const TRANSACTION_TYPES = {
  BUY: 'BUY',
  SELL: 'SELL'
};

// Delivery Types
const DELIVERY_TYPES = {
  INTRADAY: 'Intraday',
  DELIVERY: 'Delivery'
};

// Capital Gain Types
const CAPITAL_GAIN_TYPES = {
  SHORT_TERM: 'SHORT_TERM',
  LONG_TERM: 'LONG_TERM'
};

// User Roles
const USER_ROLES = {
  ADMIN: 'ADMIN',
  USER: 'USER'
};

// Status Codes
const STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  MULTI_STATUS: 207,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500
};

// Error Reason Codes
const REASON_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
};

module.exports = {
  SECURITY_TYPES,
  SECURITY_TYPES_ARRAY,
  DERIVATIVE_TYPES,
  NON_DERIVATIVE_TYPES,
  TRANSACTION_TYPES,
  DELIVERY_TYPES,
  CAPITAL_GAIN_TYPES,
  USER_ROLES,
  STATUS_CODES,
  REASON_CODES
};